#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
sed -i 's/^\(listen .*\)80/\180/' /etc/nginx/sites-available/default
ufw allow 'Nginx HTTP'
service nginx restart
echo "Hello World!" > /var/www/html/index.html
