#!/usr/bin/env bash
# install and configure an nginx server

sudo apt-get update
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
