#!/usr/bin/env bash
# generates a MySql dump and creates a compressed archive out of it

MYSQL_PASSWORD=$1
DATE=$(date +'%d-%m-%Y')
DUMP_FILENAME='backup.sql'
ARCHIVE_FILENAME="${DATE}.tar.gz"
sudo mysqldump -u root -p"${MYSQL_PASSWORD}" --all-databases > "${DUMP_FILENAME}"

sudo tar -czf "${ARCHIVE_FILENAME}" "${DUMP_FILENAME}"
