#!/usr/bin/env bash
# display the content of the /etc/passwd

passwd_file="/etc/passwd"

# Use a while loop to read and process each line of the file
while IFS=: read -r username _ uid _ _ home _; do
    	echo "Username: $username"
    	echo "User ID: $uid"
    	echo "Home Directory: $home"
done < "$passwd_file"
