#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop

counter=1
while [ $counter -le 10 ]; do
	if [ $counter -eq 9 ]; then
		echo "Best School"
		echo "Hi"	
	else
		echo "Best School"
	fi
	((counter++))
done
